name: "release"

on:
  release:
    types: [created]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install pandoc 
      run: |
        set -e
        curl -L https://github.com/jgm/pandoc/releases/download/3.1.11/pandoc-3.1.11-linux-amd64.tar.gz -o pandoc.tar.gz
        tar xvzf pandoc.tar.gz --strip-components 1 -C .

    - name: Install vessel
      run: |
        set -e
        curl -L https://github.com/dfinity/vessel/releases/download/v0.7.0/vessel-linux64 -o bin/vessel
        chmod 755 bin/vessel

    - name: Create .env.production
      run: |
        echo "PAYMENT_LINK_URL=${{ vars.PAYMENT_LINK_URL }}" > .env.production
        cat .env.production

    - name: Build release.tar.gz
      run: |
        set -e
        export PATH=$PWD/bin:$PATH
        VERSION=$(echo ${{ github.ref }} | cut -d/ -f3) make release

    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: release-*.tar.gz
        file_glob: true
